### PR TITLE
expand Travis jdk matrix with Oracle JDK 9 for Linux

### PR DESCRIPTION
**Pull request by vladak**
approaches #2513

### CODE REVIEW

**Comment by vladak** [comment]
Tried to enable Oracle JDK 11 however this failed miserably - https://travis-ci.org/vladak/OpenGrok/jobs/455513037

**Comment by vladak** [comment]
Normally, one would specify the JDK versions using `jdk:` list so that the build matrix is expanded automatically however this does not work with build stages (limitation of Travis), hence the copy-n-paste-n-modify approach.

**Comment by tulinkry** [comment]
> Tried to enable Oracle JDK 11 however this failed miserably - https://travis-ci.org/vladak/OpenGrok/jobs/455513037 <https://travis-ci.org/vladak/OpenGrok/jobs/455513037>

Isn’t is a problem of surefire? Maybe newer version? Just guessing because it doesn’t look like the problem is on our side.

**Comment by vladak** [comment]
Actually, I am going to withdraw this because the JDK 9 Linux build failed due to Coveralls Maven plugin. It was passing in my fork build which was certainly strange.

**Pull request closed without merging**
