### PR TITLE
Slightly parallelize opengrok-indexer tests

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

I'm raising this PR to see if a slight parallelization of opengrok-indexer tests succeeds on Jenkins.

I'm using 2 forks * 3 threads. Anything more, including a number of forks equal to cores, did not run reliably on my machine.

I removed `RuntimeEnvironment` dependency from a few tests. For remaining (many) tests dependent on `RuntimeEnvironment`, I decorated with `@net.jcip.annotations.NotThreadSafe` so they would not be parallelized.

Thank you.

### CODE REVIEW

**Comment by idodeclare** [comment]
Rebased for a trivial merge conflict in RepositoryFactoryTest.java

**Comment by vladak** [comment]
This aids #2964 I believe.

**Comment by idodeclare** [comment]
Rebased to see the build times subsequent to the macOS changes

**Comment by tarzanek** [comment]
hmm, the speed looks better now, gr8t! :-)

**Comment by idodeclare** [comment]
Weird ... after rebasing this is not working reliably on my MacBook anymore.

**Pull request closed without merging**
