### PR TITLE
do not hardcode exact versions in requirements.txt

### PR DESCRIPTION
**Pull request by vladak**
I don't think capturing the exact developer environment via `requirements.txt` for the Python tools is necessary. This change will make `pip install -r requirements.txt` to install whatever is in the package dependencies in `setup.py`.

### CODE REVIEW

**Comment by vladak** [comment]
Any comments @tulinkry ?

**Comment by tulinkry** [comment]
The only purpose of this file is to replicate the developer environment so there is a source of thruth when someone else is developing/debugging the code.

If you don't think capturing the env is a good idea, then this files looses its purpose and can be deleted entirely.

**Comment by vladak** [comment]
I think that's not really needed for the opengrok tools development.

**Comment by tulinkry** [comment]
Another thing which is touching this is that the versions in the setup.py should have lower and upper bounds to prevent update surprises.

**Review by tulinkry — APPROVED** [review]

**Comment by vladak** [comment]
Thanks @tulinkry !

**Pull request merged**
