### PR TITLE
Clear the type field on clear form event

### LINKED ISSUE #3028: clear button does not clear file type field
When clicking clear, all search fields are cleared but not the file type drop down.  Should clear not also reset that?

### PR DESCRIPTION
**Pull request by tulinkry**
fixes #3028

I haven't tested this in browser. Can someone pull the code and test it? It should be working.

### CODE REVIEW

**Comment by vladak** [comment]
> I haven't tested this in browser. Can someone pull the code and test it? It should be working.

does not seem to do the trick for me.

**Comment by tulinkry** [comment]
Right. The code in the type picker will clear it only when `config.multiple` is allowed (which is not for the type field).

**Comment by vladak** [comment]
> Right. The code in the type picker will clear it only when `config.multiple` is allowed (which is not for the type field).

that's tracked by #2580 BTW.

**Comment by vladak** [comment]
Superseded by #3152.

**Pull request closed without merging**
