### PR TITLE
Lucene 9.5.0

### PR DESCRIPTION
**Pull request by tarzanek**
continuation of https://github.com/oracle/opengrok/pull/3833

### CODE REVIEW

**Comment by tarzanek** [comment]
so jar and class analyzer are still broken after upgrade

**Comment by tarzanek** [comment]
but why the javadoc fails is a mystery for me
also mac build wasn't able to download some cve
@vladak any clues about above?

**Comment by vladak** [comment]
> but why the javadoc fails is a mystery for me
> also mac build wasn't able to download some cve
> @vladak any clues about above?

the CVE download problem is long standing in the macos environment and can be ignored.

**Comment by vladak** [comment]
As for the Javadoc errors, I can see these in the log:
```
/home/runner/work/opengrok/opengrok/opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/OGKUnifiedHighlighter.java:72: error: @param name not found
Error:       * @param indexSearcher a required instance
Error:                ^
Error:  /home/runner/work/opengrok/opengrok/opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/OGKUnifiedHighlighter.java:73: error: @param name not found
Error:       * @param indexAnalyzer a required instance
Error:                ^
```
Maybe the line wrapping confuses the javadoc ? (blind guess)

**Comment by tarzanek** [comment]
thnx, fixed javadocs, now I need to fix the jar and class analyzers, I have no clue why they got broken
perhaps https://github.com/oracle/opengrok/pull/3912/commits/1e1dc7c1b7cd570c22bafe59b05adb8c315506fd ?

**Comment by vladak** [comment]
rebase ?

**Comment by tarzanek** [comment]
need rebase

**Comment by tarzanek** [comment]
see https://github.com/oracle/opengrok/pull/4100#issuecomment-1411045335

**Comment by tarzanek** [comment]
actually above is relevant for jdk > jdk 11
for jdk 11 we see:
https://github.com/apache/lucene/pull/11/files
java.lang.IllegalArgumentException: Inconsistency of field data structures across documents for field [defs] of doc [1]. store term vector: expected 'true', but it has 'false'.
for the jar file

**Comment by tarzanek** [comment]
reindex is definitely needed
I fixed a bug in doc schema (for indexed jar and class files)
also format of index changed (but because of above auto upgrade won't work)

**Comment by tarzanek** [comment]
@vladak the windows tests are sloppy
and when I switched to other than jdk11 I saw weird concurrency errors
so I guess we will need to do some sanity checks on parallelism in OpenGrok
since JDK 17 and JDK 19 definitely behave in weird way with it

**Comment by tarzanek** [comment]
can you rerun the windows test @vladak ?

**Comment by tarzanek** [comment]
@ahornace any clues why those SuggesterControllerTest tests are not stable on windows ?

**Comment by vladak** [comment]
> @ahornace any clues why those SuggesterControllerTest tests are not stable on windows ?

This is #4108. I dug somewhat deep I think however haven't been able to root cause it yet.

**Comment by vladak** [comment]
> can you rerun the windows test @vladak ? (it seems like some jersey weirdness/race on windows, every x runs it reproduces)

Kicked off rerun. It fails more often than not however.

**Comment by tarzanek** [comment]
ok, failed again, so your call @vladak 
from my side this PR is ready for merge

**Comment by tarzanek** [comment]
at least the tests are stable on linux :-)
(now I am definitely done with this PR)

**Comment by vladak** [comment]
> > any clues why those SuggesterControllerTest tests are not stable on windows ?
> 
> I'm sorry, I have no idea. I agree that it shouldn't be a blocker for this change. Maybe we could disable them for Windows for now?
> 
> I don't have access to a Windows station for reproducing the issue. I will try to look into it though.

it happens on macos, although not as frequently and I was able to reproduce it on linux even when single stepping in the debugger.

**Comment by vladak** [comment]
is reindex from scratch needed ?

**Comment by tarzanek** [comment]
> is reindex from scratch needed ?

yes, unfortunately there was a bug in schema
+ this is major upgrade

**Comment by vladak** [comment]
Thanks !

**Pull request merged**
