### PR TITLE
Lucene 8.4.0

### PR DESCRIPTION
**Pull request by tarzanek**

### CODE REVIEW

**Comment by vladak** [comment]
is this backward compatible with 8.3 in terms of index ?

**Comment by tarzanek** [comment]
I think a reindex will be needed

**Comment by idodeclare** [comment]
> I think a reindex will be needed

Shouldn't it be OK without reindex? "[File formats are back-compatible between major versions. Version X.N should be able to read indexes generated by any version after and including version X&#8209;1.0...."](https://cwiki.apache.org/confluence/display/lucene/BackwardsCompatibility)

**Comment by tarzanek** [comment]
> 
> 
> > I think a reindex will be needed
> 
> Shouldn't it be OK without reindex? "[File formats are back-compatible between major versions. Version X.N should be able to read indexes generated by any version after and including version X‑1.0...."](https://cwiki.apache.org/confluence/display/lucene/BackwardsCompatibility)

the reason is just due to codec update, and I think we did 2 jumps in lucene version recently anyways (8.3 and now 8.4, so we are past 2 last versions in a short time from where I stand)

**Comment by idodeclare** [comment]
But the [PR](https://github.com/apache/lucene-solr/pull/973) for the postings format change included in 8.4 shows the previous 8.0 codec moved to backward-codecs.

backward-codecs for 8.4 include `org.apache.lucene.codecs.lucene70.Lucene70Codec` (and now `org.apache.lucene.codecs.lucene80.Lucene80Codec`) which aligns with supporting "version X&#x2011;1.0".

**Comment by tarzanek** [comment]
then it should work :-)
(but I never tested anything special and the test Vlad wrote just do basic opening of old index (which works))

**Pull request merged**
