### PR TITLE
add http header include

### PR DESCRIPTION
**Pull request by AlexandrSergei4**
Add possibility to include text from http_header_include file into the HTTP header

### CODE REVIEW

**Comment by vladak** [comment]
Hi, do you have Oracle Contributor agreement ?

**Comment by AlexandrSergei4** [comment]
Hi, I sent the email to oracle-ca_us last weekend, don't know when it will be processed

**Comment by vladak** [comment]
> Hi, I sent the email to oracle-ca_us last weekend, don't know when it will be processed

sounds good.

**Comment by idodeclare** [comment]
@AlexanderSergei4, please be sure to attend to the following:

“You must include a notice in each of Your Modifications that identifies You as the Contributor of the Modification.” —from CDDL 1.0 sec. 3.3

(“Modifications” in CDDL is source code at the file level.)

**Comment by vladak** [comment]
> I tested, and I'm good with this.
> 
> This should be squash-merged I think, as there are commits for fixes that a local build would have caught.
> 
> The linked issue will have to be manually closed.

I will merge it by hand.

**Comment by vladak** [comment]
I assume that the submitter is okay with OCA conditions (given that he claims he submitted it) so this should be ready to land. I will make sure the request gets processed (the lady who is in charge of OCAs is local).

**Comment by vladak** [comment]
Merged by hand, updated https://github.com/oracle/opengrok/wiki/Webapp-configuration

**Pull request closed without merging**
