### PR TITLE
Command expects cmd to be a list of string

### PR DESCRIPTION
**Pull request by dyno**

### CODE REVIEW

**Comment by ahornace** [comment]
I could not find your name in https://www.oracle.com/technical-resources/oracle-contributor-agreement.html
Could you please sign it? We cannot accept your change without it.

**Comment by vladak** [comment]
Modulo the Oracle Contributor Agreement this looks good to go.

**Comment by vladak** [comment]
@dyno for starters it would be good stating that you are okay with OCA terms.

**Comment by dyno** [comment]
not sure how to sign it. anyway, i am ok with the OCA terms.

**Comment by ahornace** [comment]
There are steps provided on the page I mentioned:

Submitting the OCA procedure
1. Download the OCA from here: http://www.oracle.com/technetwork/oca-405177.pdf
2. Print it
3. Fill out and sign the form (do not forget to fill in the point 7 and provide your mailing address not only your e-mail address)
4. Scan the paper
5. Send a picture/PDF to oracle-ca_us [at] oracle [dot] com

**Pull request merged**
