### PR TITLE
JSON-based web service and Eclipse plug-in

### LINKED ISSUE #45: Eclipse Plugin would be a nice enhancement
If you use eclipse, it would be nice to have a eclipse plugin for OpenGrok that supported a search interface.  Today I use opengrok in a browser, find what i want, then go back to Eclipse to locate the same file.  It would be nice if it was all inside eclipse.

Even better, if it used a google-suggest method for giving options as you typed.

Related discussion:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=162160

### LINKED ISSUE #422: provide RESTful or web-services (Bugzilla #12863)
status NEW severity _enhancement_ in component _misc_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-11-24 18:15:53 +0000, Hemang Lavana wrote:

> It would be great to have RESTful or web-services provided by the backend for search, xref, etc so that this tool can be easily integrated into other applications.

On 2009-11-25 04:52:28 +0000, Lubos Kosco wrote:

> version 0.8 (or 0.8.1) have all the pages conforming to XHTML strict (I made sure they all pass validator.w3.org ...) ... meaning that you can easily parse the data from direct http requests, since they come back as xml valid documents (hence you can just consume it like it is ;) ). The structure is obvious and we plan to stick with it (if it will be changed, we will announce it) ...
> 
> what more would we gain by implementing REST or web service ?

### PR DESCRIPTION
**Pull request by ralphmayr**
This pull request contains both a servlet that exposes OpenGroks search API via JSON (fixes #422) and a plug-in for Eclipse that uses this interface (fixes #45).

### CODE REVIEW

**Comment by cstuder** [comment]
A quick question: I cannot find any documentation about the JSON web service. How do I call this?

**Comment by tarzanek** [comment]
@cstuder /json + some params should do what you need, check this commit and check how the servlet works
Ideally if you could document it for other people who don't want to read code and perhaps for better usability, I'd be happy to accept a documentation patch, check README, ev. create a new file in doc/
tia
L

**Comment by cstuder** [comment]
Thanks for your reply. Unfortunately I'm not fluent in Java and don't know anything about servlets, but I could document the interface as soon as I figured out how to call it.

I'm using the current stable version of OpenGrok (0.12.1.5) from may 2015, am I right to assume that this merge from september 2014 is included in that release?

If yes, given a query URL like this, how do I get the results in JSON?

https://opengrok/search?q=asdf&project=name1&project=name2

**Comment by tarzanek** [comment]
looking at 0.12 stable branch I doubt it's there, please build trunk
https://github.com/OpenGrok/OpenGrok/commits/0.12-stable
0.12.x contains only small fixes, big features don't get backported

let's get
@ralphmayr to chime in - Ralph - can you help?
also ... just for clarity - wouldn't it make more sense to file a new issue as question and talk it out there?
(or I can reopen this, but this is a pull request, not a "real" bug)

**Comment by cstuder** [comment]
Oh, I see. I'll wait for it to be merged into a release then.

(I had started the discussion on this issue because I thought I just wanted to ask for clarification directly from the responsible developers...)

**Comment by tarzanek** [comment]
hehe, then @ralphmayr needs to say a word, it's his code, I just merged it ...

**Comment by vladak** [comment]
Filed #978 to track the documentation work.

**Comment by cosmoJFH** [comment]
Hi,

I would really appreciate if you could you provide some examples for this new feature. In particular I am not available to understand how to make use of the "ATTRIBUTE"s in the queries.

Cheers.

**Comment by tarzanek** [comment]
@cosmoJFH once someone replies and explains, can you update the https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-web-services wiki so everybody will be able to easier figure this out?

**Comment by cosmoJFH** [comment]
No worries, I will.

**Pull request merged**
