### PR TITLE
Feature/ctags opts

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to support customizing `Ctags` language mapping (inclusion or exclusion) per `-A,--indexer` so that Universal Ctags operation is changed too when users specify additional extensions or prefixes to map to analyzers (or unmap from them).

Thank you.

### CODE REVIEW

**Comment by idodeclare** [comment]
Rebased to fix `Ctags` conflict for `.TS` extension

**Comment by idodeclare** [comment]
Pushed a fix (with test) where a primary `LangMap` exclusion was not superseding a secondary inclusion.

**Comment by tarzanek** [comment]
lgtm, merging, thank you @idodeclare

**Comment by idodeclare** [comment]
Thank you for reviewing, @tarzanek

**Comment by tarzanek** [comment]
@idodeclare Chris, could you please look at https://travis-ci.org/oracle/opengrok/jobs/609448885 ?
it seems the ctags tests fail on mac + jdk8
after applying this patch (bad auto merge?)

**Comment by vladak** [comment]
I got ctags induced failures across the board (linux builds in Travis). I tried backing out the last changesets from HEAD to fb531549e5a28b41f197de35ff9f75f08b6039e1 and they all fail the same with stuff like:
```
Nov 11, 2019 1:48:32 PM org.opengrok.indexer.analysis.Ctags doCtags
WARNING: execution exception
java.util.concurrent.ExecutionException: java.lang.InterruptedException: tagLine == null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206
```
so it seems something changed in Univ ctags upstream.

**Comment by idodeclare** [comment]
I’m restoring my MacBook after a logic board replacement. Hopefully I’ll be up and running before too long.

Alas the large OpenGrok CI logs are not readable on my phone.

**Comment by vladak** [comment]
The Lucene 8.3 Travis build had macOS job failure due to exceeded time. I restarted the job.

**Comment by vladak** [comment]
The restarted Lucene 8.3 macOS Travis job in the end failed with the same ctags problem as above. Univ ctags at cset 89393951.

**Comment by vladak** [comment]
Seems like Univ ctags cset 9fcdb06503d82f76aebdb84de9448642a0f2d54b works fine (https://travis-ci.org/vladak/OpenGrok/builds/610394792?utm_source=github_status&utm_medium=notification). Time for `git bisect` I guess.

**Comment by vladak** [comment]
Known good Univ ctags csets:
  - be621aec
  - 9fcdb065

**Pull request merged**
