### PR TITLE
Propose fix some typos

### PR DESCRIPTION
**Pull request by jeis2497052**
Just a doc update if that is OK?

### CODE REVIEW

**Comment by vladak** [comment]
Looks like one of the tests are failing as a result of the changes:

```
[ERROR]   UtilTest.diffline:255 6,1 expected:<* An error occur[<span class="a">r</span>]ed or there is non-n...> but was:<* An error occur[r]ed or there is non-n...>
```

**Comment by jeis2497052** [comment]
OK if I revert that file?  sorry to create an issue.

**Comment by vladak** [comment]
Just fix the test instead as the typo is valid problem.

**Comment by jeis2497052** [comment]
OK, would it just be add one more r to the final string?

```
             {
-                "* An error occured or there is non-numeric stuff at the end",
                 "* An error occurred or there is non-numeric stuff at the end",
-                "* An error occured or there is non-numeric stuff at the end",
-                "* An error occur<span class=\"a\">r</span>ed or there is "
+                "* An error occurred or there is non-numeric stuff at the end",
+                "* An error occurred or there is non-numeric stuff at the end",
+                "* An error occurr<span class=\"a\">r</span>ed or there is "
                 + "non-numeric stuff at the end"
```

**Comment by idodeclare** [comment]
The test is coincidentally testing that exact typo — so I advise to leave it reverted.

**Comment by idodeclare** [comment]
It’s a diff test to be clear.

**Comment by jeis2497052** [comment]
sounds good, I will leave it reverted

**Comment by vladak** [comment]
I see, the test is checking the highlighting of the typo being corrected. Merging as is.

**Comment by vladak** [comment]
Thanks !

**Pull request merged**
