### PR TITLE
reset ctags to last known good changeset

### PR DESCRIPTION
**Pull request by vladak**
Reset Universal ctags to latest known working version.

### CODE REVIEW

**Comment by tarzanek** [comment]
were you able to figure out the upstream bug?

**Comment by vladak** [comment]
Not yet. It might be something we need to fix.

**Comment by vladak** [comment]
This is just a hot fix.

**Comment by idodeclare** [comment]
The only thing I saw from commit messages is perhaps it’s defunct now to use option such as `—C-kinds` rather than `—kinds-C`. No computer still so I can’t test yet.

**Comment by vladak** [comment]
filed #2977

**Pull request merged**
