### PR TITLE
Add more highlight colors to xref

### PR DESCRIPTION
**Pull request by tulinkry**
Adding three more colors to highlighting feature when browsing code. I run out of colors recently :-D

### CODE REVIEW

**Comment by tulinkry** [comment]
Don't merge right away, I need to test it!

**Comment by vladak** [comment]
Thanks !

**Comment by vladak** [comment]
> Don't merge right away, I need to test it!

well, if you find an error, just submit a follow-up PR.

**Comment by tulinkry** [comment]
It works, but requires forced refresh Ctrl+Shift+R in the browser (style.css changed)

**Pull request merged**
