### PR TITLE
Use git log -m, and handle octopus merges too

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to use the `-m` switch with `git log` to support octopus merges as well as to properly report if new files come into existence during a merge.

(This is an extract from a branch of mine actually named `bugfix/git_parsing` from last year which I realize now was intended at first to support the above but where I had gone down a deep rabbit hole trying to speed up history for the FreeBSD repo and arrived at several time-consuming but lackluster results. I put the branch on the back burner forgetting its original purpose.)

Users will not be forced to reindex, but any merge history previously hidden will require a reindex to be visible.

Thank you.

### CODE REVIEW

**Comment by vladak** [comment]
What happens when diffing a merge changeset and regular changeset in history view ?

**Comment by vladak** [comment]
Also, seems like there are some Windows build failures related to the changes.

**Comment by idodeclare** [comment]
> What happens when diffing a merge changeset and regular changeset in history view ?

@vladak , it's no different from any other diff. Reminder that OpenGrok starts two processes (in parallel thanks to #2955) to get the diff data for the two commit hashes. A merge has a commit hash too.

Also I pushed a change that hopefully fixes the Windows build.

**Comment by vladak** [comment]
Sounds good. Thanks !

**Comment by tulinkry** [comment]
I think this touches also #1167, @idodeclare do you think this resolves it?

**Comment by idodeclare** [comment]
> I think this touches also #1167, @idodeclare do you think this resolves it?

@tulinkry, yes I think it does.

**Comment by tulinkry** [comment]
Thanks, closing the issue

**Pull request merged**
