### PR TITLE
Fix jslint warnings

### LINKED ISSUE #2897: Fix jslint warnings
There are some warnings reported by `jslint` which might be worth looking into. Example:
```
[INFO] check file :/home/ahornace/IdeaProjects/OpenGrok/opengrok-web/src/main/webapp/js/utils-0.0.31.js
[WARNING] /home/ahornace/IdeaProjects/OpenGrok/opengrok-web/src/main/webapp/js/utils-0.0.31.js [67:50]: Line breaking error ')'.
[WARNING] ...utils-0.0.31.js:line 67:column 50:Line breaking error ')'.
	cmp = compare(array[mid], key)
[WARNING] /home/ahornace/IdeaProjects/OpenGrok/opengrok-web/src/main/webapp/js/utils-0.0.31.js [67:51]: Missing semicolon.
[WARNING] ...utils-0.0.31.js:line 67:column 51:Missing semicolon.
	cmp = compare(array[mid], key)
[WARNING] /home/ahornace/IdeaProjects/OpenGrok/opengrok-web/src/main/webapp/js/utils-0.0.31.js [81:110]: Line breaking error '0'.
[WARNING] ...utils-0.0.31.js:line 81:column 110:Line breaking error '0'.
	var myOffset = inner.$collection.first().offset() ? inner.$collection.first().offset().top : 0
[WARNING] /home/ahornace/IdeaProjects/OpenGrok/opengrok-web/src/main/webapp/js/utils-0.0.31.js [81:111]: Missing semicolon.
[WARNING] ...utils-0.0.31.js:line 81:column 111:Missing semicolon.

```

### PR DESCRIPTION
**Pull request by ahornace**
fixes #2897 

Hi,

testing performed:
- diff jumper
- navigate window
- scopes window
- message window
- hash auto scrolling
- suggestions
- select all/deselect/clear on search box
- restoreFocusAfterSearchSubmit
- toggling lines
- toggling annotations

I don't like the way I chained the function calls but `jslint` was complaining about it due to some ambiguity in automatic semicolon insertion.

I've left out warnings in searchable option list. Also, there are still some warnings produced by `yuicompressor` -> I was not trying to fix those yet.

Thanks :)

### CODE REVIEW

**Comment by vladak** [comment]
So, after this change it will be possible to run jslint as part of the build ?

**Comment by ahornace** [comment]
> So, after this change it will be possible to run jslint as part of the build ?

jslint is already running. It was implemented in https://github.com/oracle/opengrok/pull/2891

**Comment by vladak** [comment]
Ok, what about failing the build ?

Dne pá 23. 8. 2019 18:30 uživatel Adam Hornáček <notifications@github.com>
napsal:

**Comment by ahornace** [comment]
> Ok, what about failing the build ?

There is a bunch of warnings produced by yuicompressor. Namely `Try to use a single 'var' statement per scope.` which I do not know how to fix without having to declare variables at the start of the block which just seems wrong to me: https://wonko.com/post/try-to-use-one-var-statement-per-scope-in-javascript/

**Comment by vladak** [comment]
How about excluding the yuicompressor warnings for now ?

Also, needs rebase.

**Comment by ahornace** [comment]
> How about excluding the yuicompressor warnings for now ?

I don't think I can turn off the warnings without turning off the compression altogether.

http://davidb.github.io/yuicompressor-maven-plugin/compress-mojo.html

**Pull request merged**
