### PR TITLE
Add HCL and Terraform analyzers

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to add an HCL analyzer and a specialization of it for Terraform.

This patch also fixes so that `mvn test` can be repeated successfully without needing `mvn clean`. 796b45ab66 left out some needed cleanup from the setup of `-create-svn-repository`.

Thank you.

### CODE REVIEW

**Comment by tarzanek** [comment]
nice , lgtm and thanks for dividing the work in the patches, I guess this is an option to divide it into PRs if the diff is small
merge?
@vladak any comments?

**Comment by idodeclare** [comment]
> nice , lgtm 

@tarzanek , thank you for reviewing

**Comment by vladak** [comment]
quite a piece of work, thanks !

**Comment by idodeclare** [comment]
@vladak , thank you for reviewing

**Pull request merged**
