### PR TITLE
Resolve #3010 : add --nestingMaximum switch

### LINKED ISSUE #3010: History content of subdirectories (git repos) of a repoRepo Project is empty
History content of subdirectories (git repos) of a repoRepo Project is empty

Tested with both opengrok 1.3.3 and 1.3.6
OS: Ubuntu 16
tomcat 8.0.32
java-1.8.0-openjdk-amd64
git version 2.7.4

Reference: fix for bug https://github.com/oracle/opengrok/issues/2937 in 1.3.3. 
Though the history cache is now getting created for the repoRepository, the sub directories which are git repositories are getting empty History content.

I have a repoRepository project with below directory structure:
```
<SRC_ROOT>/project/
<SRC_ROOT>/project/folder1
<SRC_ROOT>/project/folder1/.git
<SRC_ROOT>/project/folder1/folder2/folder3/.git
<SRC_ROOT>/project/folder1/folder2/folder4/.git
<SRC_ROOT>/project/folder1/folder5/folder6/.git
<SRC_ROOT>/project/.repo
```
When I browse to folder1, I see History content correctly but when i click on History link on folder3, folder4, folder 6, it shows empty tables.
Added the option `--depth 6` as well but no luck.

Kindly suggest if there are additional options for nested repositories.
Indexer command used: 
```
opengrok-indexer \
    -J=-Djava.util.logging.config.file=/opengrok_1.3.6/etc/logging.properties \
    -a /opengrok_1.3.6/dist/lib/opengrok.jar -- \
    -c /usr/local/bin/ctags \
    -s /opengrok_1.3.6/src -d /opengrok_1.3.6/data -H -P -S -G \
    -W /opengrok_1.3.6/etc/configuration.xml -U http://localhost:8080/source_1.3.6 \
	--depth 6
```
image

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to add a `--nestingMaximum` switch to help user @sirisan who has a `RepoRepository` setup with two levels of nesting.

Default will continue to be just one level.

Thank you.

### CODE REVIEW

**Comment by idodeclare** [comment]
@tulinkry, thank you for the review!

**Comment by tarzanek** [comment]
lgtm, merging

**Comment by tarzanek** [comment]
thanks guys!

**Comment by idodeclare** [comment]
Thank you, @tarzanek!

**Pull request merged**
