### PR TITLE
Rejuvenate log levels

### PR DESCRIPTION
**Pull request by saledouble**
Here's a reissue of https://github.com/oracle/opengrok/pull/2754 with a new version of our tool. The tool made many fewer transformations. Again, we'd appreciate any feedback and are willing to make further changes if you wish to incorporate our PR into your project.

Settings
---
We have several analysis settings. We can vary these settings and rerun if you desire. The settings we are using in this pull request are:

- Treat CONFIG, WARNING, and SEVERE levels as a category and not a traditional level, i.e., our tool ignores these log levels.
- Never lower the logging level of logging statements within catch blocks.
- Never lower the logging level of logging statements within if statements.
- Never lower the logging level of logging statements containing certain (important) keywords.
- Never raise the logging level of logging statements without particular keywords in their messages.
- Avoid log wrapping by disregarding logging statements contained in if statements mentioning log levels.
- Adjust transformations if their transformation distances are over maximum transformation distance.

The greatest number of commits from HEAD evaluated: 5000.
The head at the time of analysis was: 0f3b14dd3a50a75033e937b1bf8e6a90bb3ee154

OCA
---
I signed and emailed the OCA to Oracle. I am also providing a written acceptance of the OCA line:

I am signing on behalf of myself as an individual and no other person or entity, including my employer, has or will have rights with respect my contributions.

### CODE REVIEW

**Comment by idodeclare** [comment]
When I see e.g. `INFO` -> `FINEST`, I'm more skeptical than e.g. `FINER` to `FINEST`. Does your tool take into account the existing log level?

**Comment by saledouble** [comment]
No, we currently do not use the existing level in our analysis. We will now add a maximum log level transformation threshold setting and edit the PR using this new setting. Thank you for your feedback.

-- @khatchad & @saledouble

**Comment by saledouble** [comment]
We have added a setting to limit the transformation distance and rerun the latest version of the tool. The transformations in this PR were updated. If there is anything we can do for the merging or feedback, please let us know. Thank you so much!

**Comment by saledouble** [comment]
I also revised the PR description to include the new setting.

**Comment by ahornace** [comment]
Closing due to inactivity and conflicts. Please resolve them and reopen.

I personally believe that log levels are sometimes a subjective thing (at least at the time of programming). Have you been using static or dynamic analysis? If you reopen the PR with conflicts resolved, then I'll gladly take a look at your tool :)

**Comment by khatchad** [comment]
Thanks, @ahornace. @saledouble is currently working on revising her thesis, but, when she is done with that, perhaps she can run the tool again on the latest HEAD and reopen and you say. Currently, we are only using static analysis, but dynamic analysis has been something we have been thinking about. Thank you again for your willingness to review our tool!

**Comment by saledouble** [comment]
Superseded by https://github.com/oracle/opengrok/pull/3617.

**Pull request closed without merging**
