### PR TITLE
bcel upgrade to 6.4.1

### PR DESCRIPTION
**Pull request by tarzanek**

### CODE REVIEW

**Comment by tarzanek** [comment]
for some unknown reason it looks like this change breaks authorization tests :-(

**Comment by idodeclare** [comment]
There is also the following:

```
[ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.782 s <<< FAILURE! - in org.opengrok.indexer.analysis.JFlexXrefTest
[ERROR] testJavaClassAnalyzer  Time elapsed: 0.162 s  <<< ERROR!
org.apache.bcel.classfile.ClassFormatException: Invalid signature: `ONSTANT_Utf8[1]("()V")'
	at org.apache.bcel.classfile.Utility.typeSignatureToString(Utility.java:1115)
	at org.apache.bcel.classfile.Utility.signatureToString(Utility.java:848)
	at org.apache.bcel.classfile.Utility.signatureToString(Utility.java:802)
	at org.opengrok.indexer.analysis.executables.JavaClassAnalyzer.constantToString(JavaClassAnalyzer.java:487)
	at org.opengrok.indexer.analysis.executables.JavaClassAnalyzer.constantToString(JavaClassAnalyzer.java:502)
	at org.opengrok.indexer.analysis.executables.JavaClassAnalyzer.getContent(JavaClassAnalyzer.java:409)
	at org.opengrok.indexer.analysis.executables.JavaClassAnalyzer.analyze(JavaClassAnalyzer.java:136)
	at org.opengrok.indexer.analysis.executables.JavaClassAnalyzer.analyze(JavaClassAnalyzer.java:112)
	at org.opengrok.indexer.analysis.JFlexXrefTest.testJavaClassAnalyzer(JFlexXrefTest.java:511)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

**Comment by tarzanek** [comment]
hmm, build now failed on some windows unrelated thing - @vladak do I need to fix it or can we merge this?

**Comment by vladak** [comment]
> hmm, build now failed on some windows unrelated thing - @vladak do I need to fix it or can we merge this?

The Windows build error is unrelated.

**Comment by vladak** [comment]
You going to add a copyright ?

**Comment by tarzanek** [comment]
what copyright?

**Comment by vladak** [comment]
> what copyright?

```java

/*
 * Copyright (c) 2005, 2019, Oracle and/or its affiliates. All rights reserved.
 * Portions Copyright (c) 2018-2019, Chris Fraire <cfraire@me.com>.
 */
```

**Comment by tarzanek** [comment]
sounds good to me, I don't insist on putting my name there
I hope I can do it ;-)
(you should be free to do this I hope and choose ignorance, git history has a list of authors anyways)

**Comment by vladak** [comment]
> sounds good to me, I don't insist on putting my name there
> I hope I can do it ;-)
> (you should be free to do this I hope and choose ignorance, git history has a list of authors anyways)

see https://github.com/oracle/opengrok/pull/3069#issuecomment-597682578

**Comment by tarzanek** [comment]
> 
> 
> > sounds good to me, I don't insist on putting my name there
> > I hope I can do it ;-)
> > (you should be free to do this I hope and choose ignorance, git history has a list of authors anyways)
> 
> see [#3069 (comment)](https://github.com/oracle/opengrok/pull/3069#issuecomment-597682578)

noooooooooooooooooooooooooooooo
:-D

**Comment by tarzanek** [comment]
@idodeclare Chris, come on, tell me we can ignore it, I choose freedom :-)

Can we switch license to http://www.wtfpl.net/ ? :-P

**Comment by idodeclare** [comment]
😁

CDDL doesn’t demand you assert copyright. 

That excerpt I had quoted, however, is from a section titled “Required Notices.” It would suffice to note “by tarzanek” I believe.

**Comment by tarzanek** [comment]
updated with copyright

**Comment by vladak** [comment]
Now you're truly on the other side :-)

**Pull request merged**
