### PR TITLE
Fixing get_repo_type params

### PR DESCRIPTION
**Pull request by tulinkry**
Introduced in #3259

### CODE REVIEW

**Comment by tulinkry** [comment]
I realize this is not actually fixing the problem, as `params` is not a parameter anymore.

**Comment by tulinkry** [comment]
0a7c44226b813ef14a8cf77d1b4fb8c14e69994a should do it

**Comment by tulinkry** [comment]
fixes #3273

**Comment by vladak** [comment]
Thanks ! Obviously this area needs more test coverage.

**Pull request merged**
