### PR TITLE
Add demo link to README

### PR DESCRIPTION
**Pull request by Orviss**
If you would like to change the order then let me know :) I had no idea where to put it so I appended it to the end.

Thanks :)

### CODE REVIEW

**Comment by vladak** [comment]
I wonder if there is a button similar to coverage/build status.

**Comment by Orviss** [comment]
I was looking at it and I was not able to find "Demo" one. However, it is customizable so it is easy to create it.

**Comment by Orviss** [comment]
<http://shields.io/#your-badge> However, I'm not exactly sure what to specify as a status. Maybe online/offline ? Still, this would probably require some file hosting where this badge would be accessible and we could swap it by periodically checking the server? Or am I just complicating things and it could be done in a different manner?

**Comment by tulinkry** [comment]
By the way, the demo has some problems: http://demo.opengrok.org/xref/opengrok/web/js/utils-0.0.22.js?r=38f77573 (no content)

**Comment by Orviss** [comment]
Should be working now, xref was not created somehow. I have a pipeline in Jenkins which clones the project, builds it, runs `sync.py`, gets new config and deploys the new webapp. However, this does not work always as it should...

**Pull request merged**
