### PR TITLE
DEFS stores true offsets from enhanced CtagsReader

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to enhance `CtagsReader` to store true posting for `DEFS` for use by the `UnifiedHighlighter` — i.e. so that a document is not required to be re-analyzed to present `DEFS` search matches.

Because of limitations in ctags results (e.g. partial patterns or truncated patterns) and limitations in the ctags format itself (e.g., having line numbering but no character offsets as required for Lucene postings), `CtagsReader` is enhanced to supplement the tags *when necessary* with additional analysis of the source text.

E.g., in `sample.cc`/`sampletags_cc`, the function definition (excluding body) for `definitionContains()` spans seven lines in source code:
```
int
Ancestor::definitionContains(const fru_regdef_t *def,
				const fru_regdef_t *parent_def,
				Str element,
				uint32_t offset,
				Ancestor *ant,
				Str path)
```
 but Universal Ctags only produces a pattern for one line of the definition:
```
/^Ancestor::definitionContains(const fru_regdef_t *def,$/;"
```
and ctags presents a `signature` with modified cstyle (note the different whitespace around asterisks and commas):
```
(const fru_regdef_t * def,const fru_regdef_t * parent_def,Str element,uint32_t offset,Ancestor * ant,Str path)
```

`CtagsReader` is enhanced to analyze the text in various ways to arrive at the best Lucene postings given the ctags variances.

`CtagsReader` is also enhanced to be project tabsize-aware or else postings would be mistakenly shifted when a non-zero project tab size is defined.

Thank you.

### CODE REVIEW

**Comment by vladak** [comment]
I wonder if this will fix issues like  #1374.

Dne 6. 3. 2018 9:01 odp. napsal uživatel "C Fraire" <
notifications@github.com>:

**Comment by idodeclare** [comment]
> I wonder if this will fix issues like  #1374.

I wrote on that issue last month that this PR will provide an avenue to address the problem.

**Comment by tarzanek** [comment]
thank you Chris, this is a good start, I have finally read it, 
I am not sure on few things (like if we need all those tokenstream wrappers, I was under the impression lucene is trying to simplify this and get rid of custom Tokenstreams, but in our case this is a bit of problem)
let's merge it
I have also some concerns about performance impact (both with tabs), but then all the info we gain is vital, so let's give it a shot

thank you
L

**Comment by idodeclare** [comment]
Thank you for the review, Lubos.

> if we need all those tokenstream wrappers, I was under the impression lucene is trying to simplify this and get rid of custom Tokenstreams

I am not sure if Lucene will get rid of custom token streams or make it even easier to use `Tokenizer`-based classes (e.g. `JFlexTokenizer`) that take `Reader` instances as input. For a token enumeration that uses alternate source data (as for this patch that sources ctags `Definitions`), I still think from studying the Lucene API docs that a custom `TokenStream` subclass is appropriate.

As for performance, I am concerned as well, but the only optimization path short of replacing ctags is external to OpenGrok: i.e. enhancing Universal ctags to augment the tags data to support more granular and more comprehensive metadata in tags (namely character offsets, full multi-line patterns, and perhaps "`true_signature`" that reflects actual source code).

Anyway, I am glad because having this and #2035 merged allows me to raise the PR for the incorporation of `UnifiedHighlighter`.

**Comment by idodeclare** [comment]
(BTW I have two small concerns with Github "Rebase and merge": 1] the commits go in without log text referring to the original PR#; and 2] for a multi-commit branch, it would make any git-revert [thankfully rare] more difficult since there would not be a single merge-commit to revert.)

**Comment by tarzanek** [comment]
AH!
sorry for that, I will try to avoid rebase and merge, my fault
github recently switched the merge UI , so I will try to find a better way (resp. stick to original way which preserved everything) , it might involve a bit of testing, so I hope you don't mind me using you as guinea pig ;)

**Comment by tarzanek** [comment]
regarding universal ctags - I think those guys do a very good job, it makes sense to file issues with them, they are very responsive and helpful

**Pull request merged**
