### PR TITLE
opengrok web project code smell fixes

### PR DESCRIPTION
**Pull request by ginoaugustine**

### CODE REVIEW

**Review by vladak — CHANGES_REQUESTED** [review]
For the JS changes, it would be good to rename+bump version and do the appropriate change in https://github.com/oracle/opengrok/blob/78ad87a5a965eb7196d253a3b399c6163b6b8656/opengrok-web/src/main/java/org/opengrok/web/Scripts.java#L112-L125

**Comment by ginoaugustine** [comment]
> For the JS changes, it would be good to rename+bump version and do the appropriate change in
> 
> https://github.com/oracle/opengrok/blob/78ad87a5a965eb7196d253a3b399c6163b6b8656/opengrok-web/src/main/java/org/opengrok/web/Scripts.java#L112-L125

Done

**Review by vladak — APPROVED** [review]

**Comment by vladak** [comment]
Can you do some casual testing of the UI ? Specifically for the JS libraries that changed.

**Comment by ginoaugustine** [comment]
> Can you do some casual testing of the UI ? Specifically for the JS libraries that changed.

Tested loading of projects in home page and disable of any messages based upon the tag.
Tested table sorting based upon date.
File Type search

**Pull request merged**
