### PR TITLE
Improve configuration help

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to improve `--help --detailed` as shown below:

Thank you.

**ignoredNames**
Former:
```
  <!-- Sample for setIgnoredNames. Default is: org.opengrok.indexer.index.IgnoredNames@638ef7ed -->
```
New:
```
  <!-- Sample for setIgnoredNames. Default is OpenGrok's standard set of ignored
       files and directories -->
```

**includedNames**
Former:
```
  <!-- Sample for setIncludedNames. Default is: org.opengrok.indexer.index.Filter@14f232c4 -->
```
New:
```
  <!-- Sample for setIncludedNames. Default is an empty filter -->
```

**pluginStack**
Former:
```
  <!-- Sample for setPluginStack. Default is: org.opengrok.indexer.authorization.AuthorizationStack@2072acb2 -->
```
New:
```
  <!-- Sample for setPluginStack. Default is an empty stack -->
```

**suggesterConfig**
Former:
```
  <!-- Sample for setSuggesterConfig. Default is: org.opengrok.indexer.configuration.SuggesterConfig@6eea4a46 -->
<?xml version="1.0" encoding="UTF-8"?>
<java version="1.8.0_222-internal" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration"/>
</java>
```
New:
```
  <!-- Sample for setSuggesterConfig. Default is as below but with Boolean
       opposites, non-zeroes decremented by 1, null for allowed-projects, and
       also including "full" in allowed-fields -->
  <void property="suggesterConfig">
   <void property="allowComplexQueries">
    <boolean>false</boolean>
   </void>
   <void property="allowMostPopular">
    <boolean>false</boolean>
   </void>
   <void property="allowedFields">
    <object class="java.util.HashSet">
     <void method="add">
      <string>defs</string>
     </void>
     <void method="add">
      <string>path</string>
     </void>
     <void method="add">
      <string>hist</string>
     </void>
     <void method="add">
      <string>refs</string>
     </void>
     <void method="add">
      <string>type</string>
     </void>
    </object>
   </void>
   <void property="allowedProjects">
    <object class="java.util.HashSet">
     <void method="add">
      <string>project-1</string>
     </void>
     <void method="add">
      <string>project-2</string>
     </void>
    </object>
   </void>
   <void property="buildTerminationTime">
    <int>1801</int>
   </void>
   <void property="enabled">
    <boolean>false</boolean>
   </void>
   <void property="maxProjects">
    <int>32768</int>
   </void>
   <void property="maxResults">
    <int>11</int>
   </void>
   <void property="minChars">
    <int>1</int>
   </void>
   <void property="rebuildCronConfig">
    <string>1 0 * * *</string>
   </void>
   <void property="rebuildThreadPoolSizeInNcpuPercent">
    <int>81</int>
   </void>
   <void property="showProjects">
    <boolean>false</boolean>
   </void>
   <void property="showScores">
    <boolean>true</boolean>
   </void>
   <void property="showTime">
    <boolean>true</boolean>
   </void>
   <void property="timeThreshold">
    <int>2001</int>
   </void>
  </void>
```

### CODE REVIEW

**Comment by tarzanek** [comment]
merging, thank you Chris!

**Comment by idodeclare** [comment]
Thank you, @tarzanek!

**Comment by naseer-nv** [comment]
How can I see this help ? I don't see a `--detailed` flag

**Comment by vladak** [comment]
> How can I see this help ? I don't see a `--detailed` flag

In the current version that would be `--help config`.

**Comment by naseer-nv** [comment]
it doesn't show up - instead suggester config shows up with every single property

example

```xml
opengrok-indexer  -a $DATA/dist/latest/lib/opengrok.jar -- --help config
Nov 23, 2023 12:41:09 PM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [--help, config]
Configuration examples:

<!-- Sample empty configuration.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<java version="11.0.20.1" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
  <void id="SuggesterConfig0" property="suggesterConfig">
   <void property="allowedFields">
    <void method="clear"/>
    <void method="add">
     <string>defs</string>
    </void>
    <void method="add">
     <string>path</string>
    </void>
    <void method="add">
     <string>hist</string>
    </void>
    <void method="add">
     <string>refs</string>
    </void>
    <void method="add">
     <string>type</string>
    </void>
    <void method="add">
     <string>full</string>
    </void>
   </void>
  </void>
 </object>
</java>

  <!-- Sample for setAllowedSymlinks. Default is [] -->
  <void property="allowedSymlinks">
   <void method="add">
    <string>user-defined-element</string>
   </void>
  </void>
  <void id="SuggesterConfig0" property="suggesterConfig">
   <void property="allowedFields">
    <void method="clear"/>
    <void method="add">
     <string>defs</string>
    </void>
    <void method="add">
     <string>path</string>
    </void>
    <void method="add">
     <string>hist</string>
    </void>
    <void method="add">
     <string>refs</string>
    </void>
    <void method="add">
     <string>type</string>
    </void>
    <void method="add">
     <string>full</string>
    </void>
   </void>
  </void>

```






version
```
opengrok-indexer  -a $DATA/dist/latest/lib/opengrok.jar -- --version
Nov 23, 2023 12:42:31 PM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [--version]
OpenGrok v1.12.23 rev 774e4ae2f505a4c2a6765feed7ca2782e44f8075

```



I can fork this off into a new bug if needed

**Comment by vladak** [comment]
> I can fork this off into a new bug if needed

Please do.

**Pull request merged**
