### PR TITLE
run Jacoco and publish the results to Coveralls.io

### PR DESCRIPTION
**Pull request by vladak**
Enables Jacoco proper, publishes results to [Coveralls.io](https://coveralls.io/repos) (I enabled the oracle/opengrok repo there).

Used resources:
  - https://angus.nyc/2015/continuous-integration-for-java-github
  - https://stackoverflow.com/questions/12269558/maven-jacoco-plugin-error
  - https://github.com/onelogin/java-saml/issues/74

### CODE REVIEW

**Comment by tarzanek** [comment]
looks good, let's merge ... I guess coveralls will be part of checks now?

**Comment by vladak** [comment]
It will display the coverage nicely for each build, the actual threshold
enforcement is up to us. In an ideal world the difference for each pull
request would be checked automatically however that would require some sort
of API from Coveralls + associated scripting. Not worth doing now I guess.

Dne čt 19. 4. 2018 15:40 uživatel Lubos Kosco <notifications@github.com>
napsal:

**Comment by tarzanek** [comment]
we have more such tools in https://github.com/oracle/opengrok/wiki/How-to-build-OpenGrok-from-source
coverity is there too .. (but not sure if it is up to date)

**Comment by tarzanek** [comment]
isn't the plugin you use a bit out of date ?
per https://www.versioneye.com/user/projects/54b7a584050646ca5c0001aa
?

**Comment by vladak** [comment]
Possibly. That might be true for other plugins as well.

Dne čt 19. 4. 2018 17:33 uživatel Lubos Kosco <notifications@github.com>
napsal:

**Comment by vladak** [comment]
Yep. Not sure the rest can be integrated as well as Jacoco, though.

Dne čt 19. 4. 2018 17:29 uživatel Lubos Kosco <notifications@github.com>
napsal:

**Pull request merged**
