### PR TITLE
Jakartify - update to Jersey 3, Tomcat 10

### PR DESCRIPTION
**Pull request by ahornace**
I just wanted to update Jersey but had to continue with the jakartification of the whole project. Main benefits:
- Tomcat 10
- Servlet API 5
- Jersey 3

I've just done some basic testing - indexed one project and tested search. More thorough testing will be needed.

I still cannot build docker locally due to https://github.com/oracle/opengrok/issues/3291 @vladak could you please test it?

Thanks.

### CODE REVIEW

**Comment by vladak** [comment]
Does this mean that Tomcat 10 will become the lowest supported version ?

**Review by vladak — APPROVED** [review]
I don't see any significant changes besides the imports/GenericType.

**Comment by ahornace** [comment]
> Does this mean that Tomcat 10 will become the lowest supported version ?

Yes, it does. However, Tomcat 10 still requires Java 8 as a minimum Java version so the migration should not cause many problems.

> I don't see any significant changes besides the imports/GenericType.

Yes, the imports changed due to some licensing problems when Jakarta EE is not allowed to use `javax` package so everything had to be moved.

**Comment by vladak** [comment]
https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok will need to be updated.

**Comment by vladak** [comment]
Trying the Docker image, fails with:
``
opengrok-tomcat-10 | 2021-02-16 14:11:38 Waiting for Tomcat startup...
opengrok-tomcat-10 | NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.230 WARNING [main] org.apache.tomcat.util.digester.Digester.endElement No rules found matching [Server/Service/Engine/Host/Disabled]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.233 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.0.2
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.233 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jan 28 2021 18:48:46 UTC
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.233 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.0.2.0
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-65-generic
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.10+9
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.246 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.26] using APR version [1.6.5].
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.246 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.248 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.543 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.562 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [461] milliseconds
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.605 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.605 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.2]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.624 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.636 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Context] failed to set property [antiJARLocking] to [true]
opengrok-tomcat-10 | 16-Feb-2021 14:11:39.874 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
opengrok-tomcat-10 | 	java.lang.IllegalStateException: Error starting child
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
opengrok-tomcat-10 | 		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:946)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1792)
opengrok-tomcat-10 | 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
opengrok-tomcat-10 | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
opengrok-tomcat-10 | 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
opengrok-tomcat-10 | 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:757)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1520)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
opengrok-tomcat-10 | 		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
opengrok-tomcat-10 | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
opengrok-tomcat-10 | 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
opengrok-tomcat-10 | 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
opengrok-tomcat-10 | 		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok-tomcat-10 | 		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok-tomcat-10 | 		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
opengrok-tomcat-10 | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
opengrok-tomcat-10 | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
opengrok-tomcat-10 | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
opengrok-tomcat-10 | 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
opengrok-tomcat-10 | 	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
opengrok-tomcat-10 | 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
opengrok-tomcat-10 | 		... 37 more
opengrok-tomcat-10 | 	Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletContainerInitializer
opengrok-tomcat-10 | 		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
opengrok-tomcat-10 | 		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
opengrok-tomcat-10 | 		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
opengrok-tomcat-10 | 		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2433)
opengrok-tomcat-10 | 		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:864)
opengrok-tomcat-10 | 		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
opengrok-tomcat-10 | 		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
opengrok-tomcat-10 | 		at java.base/java.lang.Class.forName0(Native Method)
opengrok-tomcat-10 | 		at java.base/java.lang.Class.forName(Class.java:398)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:226)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:197)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1840)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1298)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:986)
opengrok-tomcat-10 | 		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:303)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
opengrok-tomcat-10 | 		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5031)
opengrok-tomcat-10 | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok-tomcat-10 | 		... 38 more
opengrok-tomcat-10 | 	Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContainerInitializer
opengrok-tomcat-10 | 		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
opengrok-tomcat-10 | 		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
opengrok-tomcat-10 | 		... 56 more
```

**Comment by vladak** [comment]
Also, I asked around and it does not seem there will be any update to Tomcat in Solaris (currently there is just Tomcat 8) and the answer is no (because of Jakarta 10) which makes me worry about my internal deployment.

**Comment by ahornace** [comment]
> Trying the Docker image, fails with:

Thanks, I will take a look. I'll skip the build part and just try the deployment.

> Also, I asked around and it does not seem there will be any update to Tomcat in Solaris (currently there is just Tomcat 8) and the answer is no (because of Jakarta 10) which makes me worry about my internal deployment.

Hmm, you are right :( we don't have to push this and put this on hold for at least a while until the update will be necessary.

**Comment by vladak** [comment]
> > Also, I asked around and it does not seem there will be any update to Tomcat in Solaris (currently there is just Tomcat 8) and the answer is no (because of Jakarta 10) which makes me worry about my internal deployment.
> 
> Hmm, you are right :( we don't have to push this and we can put this on hold for at least a while until the update will be necessary.

I don't have a problem running Tomcat version not shipped with the system. It just has to work on Solaris. After all I am already running Tomcat 8 with compiled Java 11 on Solaris and it works fine.

**Comment by vladak** [comment]
After learning that Tomcat 10 supports Java 8 (Solaris stuck with Java 8 forever), @psumbera (Apache / Tomcat maintainer for Solaris) said he will take a look so this removes the blocker for me.

**Comment by ahornace** [comment]
The docker image works for me now. However, I noticed that suggester is not initialized properly due to asynchronous indexing. It will not be able to read the index for the dummy project at startup and ignore all the fields onwards. I will look into it. However, I will create a separate PR for that as it is related to https://github.com/oracle/opengrok/pull/3402 and not this one.

**Comment by vladak** [comment]
Thanks !

**Pull request merged**
