### PR TITLE
Don't select line numbers when highlighting code

### PR DESCRIPTION
**Pull request by thecodeboss**
When you copy and paste code results from OpenGrok, it will no longer copy the line numbers with this change.

Will save us the trouble of having to view the raw file before copying.

### CODE REVIEW

**Comment by tulinkry** [comment]
I think that the line numbers are there by design. If you need the code directly you go to raw.

**Comment by vladak** [comment]
It is definitely intention to have the line numbers to be copied to the buffer, at least in the normal view mode. Perhaps change is targeting some other mode (diff, search) ? (have not have the time to try it out yet)

**Comment by thecodeboss** [comment]
> I think that the line numbers are there by design. If you need the code directly you go to raw.

This doesn't seem like a very good design. On GitHub if you copy code it never includes the line numbers, and it's the same with basically every code editor or code viewer out there.
Having to go to the raw mode to copy code is especially annoying because you no longer have line numbers to refer to, and it's hard to find the code you were trying to copy. You also lose the syntax highlighting.
If there's still disagreement, maybe it is worth adding a checkbox that says something along the lines of "Include line numbers when copying" so power users can copy without having to go to raw mode.

**Comment by vladak** [comment]
Having the ability to select the line numbers is still important in many deployments where code is pasted say to a bug tracking system which then includes comments referencing the line numbers. I can still see this being used heavily, at least in our environment.

There is actually a 'Line#' link at the top of the page which enables/disables line numbers, does this do the trick for you ?

**Comment by thecodeboss** [comment]
> There is actually a 'Line#' link at the top of the page which enables/disables line numbers, does this do the trick for you ?

Ah yes actually, this is a nice trick. Maybe it should say "Toggle line numbers" instead of just "Line#" to make it more obvious what it does.

**Comment by vladak** [comment]
I'd like to keep it short. The UI should be minimalistic I think. There is a help bubble that explains what it does if you do mouse over.

**Pull request closed without merging**
