### PR TITLE
making protected constant again public

### PR DESCRIPTION
**Pull request by tulinkry**

### CODE REVIEW

**Comment by vladak** [comment]
what is the reason for this change ?

**Comment by tulinkry** [comment]
check #dev channel on slack

**Comment by tulinkry** [comment]
the reason is that in https://github.com/oracle/opengrok/pull/2507/commits/76e97724efa6dc7474d43bc22d46854818f706a3 I accidentally changed the cookie name constant visibility

**Comment by vladak** [comment]
I see, fails to compile the JSP now.

st 14. 11. 2018 9:07 odesílatel Kryštof Tulinger <notifications@github.com>
napsal:

**Pull request merged**
