### PR TITLE
Feature/more tests

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to add xref tests for Lisp, Pascal, Troff, and XML (but skipping for now a comprehensive review as I've done for other languages).

The patch also includes the following fix-ups:

* Update to use actual ctags output of sample.php.
* Retire `PhpXrefSpanner`, and move methods into `PhpXref`.
* Eliminate some PHP `<em>` and `<strong>` styling around `writeSymbol()` calls, which differs from all other lexers (and won't be supported by `JFlexSymbolMatcher`).
* Rewrite the very few `<i>` stylings as `<em>` for consistency with other language lexers.
* Rewrite all remaining `<em>` and `<strong>` stylings in language lexers as single statements with triple `append()`s (for easier systematic revision at a later point).
* Use `disjointSpan()` in `LispXref`, `PascalXref`, `XMLXref`. 

Thank you.

### CODE REVIEW

**Comment by tarzanek** [comment]
sorry for a late reply, let me check some of the PRs and continue the flow

**Comment by tarzanek** [comment]
lgtm, thank you for your patience @idodeclare 
it would be cool if you could review stuff too, would you mind if you would get reviewer/merger permissions ? 
(once we sort out oracle admin settings ? )

**Comment by tarzanek** [comment]
merging, thank you!

**Comment by idodeclare** [comment]
Thank you, @tarzanek !

Yes I can certainly participate as a reviewer.

**Pull request merged**
