### PR TITLE
Update jQuery UI to 1.12.1

### PR DESCRIPTION
**Pull request by Orviss**
For suggester `Autocomplete` widget from jQuery UI is needed. So I added it and also upgraded the version when I was at it.

Basic functionality seems to work. I also tried dragging and that worked too.

Thanks :)

### CODE REVIEW

**Comment by tulinkry** [comment]
maybe also check the diff jumper, I don't remember if it has the dependency

**Comment by Orviss** [comment]
Jumper seems to work properly as well.

**Comment by tulinkry** [comment]
And I assume console doesn't show any warnings .. ?

**Comment by Orviss** [comment]
Does not seems so 
screen shot 2018-05-30 at 09 35 34

**Pull request merged**
