### PR TITLE
Fix #770 Fix #1351 : use PathAccepter in FileHistoryCache

### LINKED ISSUE #770: Ignore history indexing of repositories matching IGNORE_PATTERNS
This is related to https://github.com/OpenGrok/OpenGrok/issues/652.
 When indexing an Android repo, there are certain projects that have large binary files such as prebuilts/ndk which aren't necessary to index. Putting such directories in the ignore patterns skips the source indexing for that directory but the history index is still created. The history caching can sometimes take upwards of 30 minutes for such repositories.
Use IGNORE_PATTERNS or some similar mechanism to skip history indexing of these repos.

### LINKED ISSUE #1351: The history generation does not respect ignored files/dirs and symlinks
Discovered while solving #1315.

Reproducible with steps:
```bash
mkdir repo
cd repo
git init
mkdir foo
touch main.c
git add .
git commit -m "commit"
```

Then run the indexer with an `-i main.c` switch to ignore such file. Investigating the data directory, there is a record for main.c in the historycache.

 - hitting http://localhost:8080/source/history/repo/main.c works (as unexpected) and shows the commit
 - hitting http://localhost:8080/source/xref/repo/main.c doesn't (as expected)

I believe the same works for `acceptedSymlinks` as the code lacks this code as well.

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to extract a small bit of logic from `IndexDatabase` so that history generation will respect ignored files/dirs as well as explicitly included files.

The symlink logic from `IndexDatabase` does not have to be lifted out, since history generation already handles `ForbiddenSymlinkException`. Including the symlink itself as a listed file in history is not an issue.

Also, this patch relocates `Filter`, `IgnoredDirs`, `IgnoredFiles`, and `IgnoredNames` to `configuration`.

Thank you.

### CODE REVIEW

**Comment by tarzanek** [comment]
sorry, did it again, merged your other patch and created conflicts
tia for rebase

**Comment by idodeclare** [comment]
> sorry, did it again, merged your other patch and created conflicts
> tia for rebase

No worries, Lubos. Now rebased (just conflicts in copyright — your favorite). Thank you for taking a look.

**Comment by idodeclare** [comment]
Oh no I tried the Github conflict resolver, but I don't like that it merged master into this branch. I'm revising....

**Comment by idodeclare** [comment]
It was just a tiny conflict in `RuntimeEnvironment`.

**Comment by idodeclare** [comment]
Rebased for minor conflicts after #3154

**Comment by idodeclare** [comment]
Just resolving a conflict in copyright...

**Comment by vladak** [comment]
Looks quite clean, thanks !

**Comment by idodeclare** [comment]
Thank you, @vladak!

**Pull request merged**
